services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - ./data-mongo/db:/data/db
      - ./data-mongo/config:/etc/mongod.conf
    ports:
      - 2717:27017
    restart: unless-stopped
    networks:
      - lab-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge